---
# tasks file for ansible-nginx

- name: setup key
  apt_key:
    url: "{{ nginx_key }}"

- name: add repository
  apt_repository:
    repo: "{{ item }}"
  with_items:
    - "deb http://nginx.org/packages/debian/ {{ ansible_distribution_release }} nginx"
    - "deb-src http://nginx.org/packages/debian/ {{ ansible_distribution_release }} nginx"
  when: ansible_distribution == 'Debian'

- name: add repository
  apt_repository:
    repo: "{{ item }}"
  with_items:
    - "deb http://nginx.org/packages/ubuntu/ {{ ansible_distribution_release }} nginx"
    - "deb-src http://nginx.org/packages/ubuntu/ {{ ansible_distribution_release }} nginx"
  when: ansible_distribution == 'Ubuntu'

- name: install latest version
  apt:
    name: nginx
    update_cache: yes
    cache_valid_time: 3600
    state: latest
  notify: restart nginx

- name: create directories
  file:
    state: directory
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - '{{ nginx_configs_dir }}'
    - '{{ nginx_snippets_dir }}'
    - '{{ nginx_site_available_dir }}'
    - '{{ nginx_site_enabled_dir }}'

- stat:
    path: "{{ nginx_configs_dir }}/default.conf"
  register: nginx_conf_st

- name: forward default.conf to new config directory
  command: "mv {{ nginx_configs_dir }}/default.conf {{ nginx_site_available_dir }}/"
  when: nginx_conf_st.stat.exists

- name: enable default site
  file:
    state: link
    src: '{{ nginx_site_available_dir }}/default.conf'
    dest: '{{ nginx_site_enabled_dir }}/default.conf'
  notify: restart nginx
  when: nginx_enable_defualt_site

- name: disable default site
  file:
    state: absent
    path: '{{ nginx_site_enabled_dir }}/default.conf'
  notify: restart nginx
  when: nginx_enable_defualt_site == False

- name: update nginx.conf
  tags:
    - nginx-conf
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: update SSL options
  tags:
    - nginx-conf
  template:
    src: ssl-params.conf
    dest: '{{ nginx_configs_dir }}/ssl-params.conf'
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: generate Diffie–Hellman key
  command: openssl dhparam -out {{ nginx_ssl_dhparam_file }} 2048
  args:
    creates: "{{ nginx_ssl_dhparam_file }}"
