---
# tasks file for ansible-nginx

- name: install latest version
  apt:
    name: nginx
    update_cache: yes
    cache_valid_time: 3600
    state: latest
  notify: restart nginx

- name: update nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nginx
